name: Auto Commit

on:
  schedule:
    - cron: '0 0 * * 1,4,6'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make a commit
        run: |
          git config user.name "Ze-rith"
          git config user.email "221796529+Ze-rith@users.noreply.github.com"
          date >> log.txt
          git add log.txt
          git commit -m "chore: auto commit $(date +'%Y-%m-%d')"
          git push
